import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ComponentContextProvider } from '../../context/component.context'
import { NotifierContextProvider } from '../../context/notifier.context'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ComponentContextProvider>
        <NotifierContextProvider>
        <body className={inter.className}>{children}</body>
        </NotifierContextProvider>
      </ComponentContextProvider>
    </html>
  )
}
